const catalogoTeclados = [
  {
    id: 1,
    marca: "RK Royal Kludge",
    modelo: "RK61",
    tipoSwitch: "Blue Switch",
    formato: "60%",
    precio: 49.99,
    disponible: true,
    imagen: "image/Keyboards/Catalogo/rk61/RK61_6_Wireless_Mechanical_Keyboard.jpg",
  },
  {
    id: 2,
    marca: "RK Royal Kludge",
    modelo: "M87 TKL",
    tipoSwitch: "Cream Switch",
    formato: "80%",
    precio: 89.99,
    disponible: true,
    imagen: "image/Keyboards/Catalogo/m87/M87_TKL_Wireless_Gaming_Keyboard.jpg",
  },
  {
    id: 3,
    marca: "Attack Shark Ajazz",
    modelo: "Ak820",
    tipoSwitch: "Sea Salt Switch",
    formato: "75%",
    precio: 39.99,
    disponible: true,
    imagen: "image/Keyboards/Catalogo/ak820/Attack_Shark_Ajazz_Ak820.jpg",
  },
  {
    id: 4,
    marca: "Terport",
    modelo: "TR95-E150",
    tipoSwitch: "Huano Red Switch",
    formato: "90%",
    precio: 49.99,
    disponible: true,
    imagen: "image/Keyboards/Catalogo/tr95/TERPORT_90_TR95-E150.jpg",
  },
];
